version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB : devise_test_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5555:5432'

  redis:
    image: redis
    command: redis-server
    ports:
      - '6888:6379'

